language: python

python:
  - "2.7"
  - "3.5"

install:
  - pip install flake8

script:
- flake8 --max-line-length=120 --exclude=./instagram_private_api/compat.py,./instagram_web_api/compat.py,./instagram_private_api/endpoints/__init__.py
- python -m compileall -q instagram_web_api instagram_private_api examples tests

branches:
  only:
    - master
